In [3]:
import tensorflow as tf

In [4]:
print(tf.__version__)

2.0.0-alpha0


In [5]:
hello = tf.constant('Hello ')

In [6]:
world = tf.constant('World')

In [7]:
type(hello)

tensorflow.python.framework.ops.EagerTensor

In [8]:
hello

<tf.Tensor: id=0, shape=(), dtype=string, numpy=b'Hello '>

In [9]:
tf.print(hello)

Hello 


In [10]:
tf.print(hello + world)

Hello World


In [11]:
res = hello + world

In [12]:
res

<tf.Tensor: id=4, shape=(), dtype=string, numpy=b'Hello World'>

In [14]:
tf.print(res)

Hello World


In [15]:
a = tf.constant(10)

In [16]:
b = tf.constant(20)

In [17]:
c = a + b

In [18]:
c

<tf.Tensor: id=8, shape=(), dtype=int32, numpy=30>

In [19]:
tf.print(c)

30


In [20]:
const = tf.constant(10)

In [21]:
fill_mat = tf.fill((4,4),10)

In [22]:
myseros = tf.zeros((4,4))

In [23]:
ones = tf.ones((4,4))

In [32]:
rand = tf.random_normal_initializer(mean=0, stddev=1.0).__call__((4,4))

In [34]:
rand_unif = tf.random_uniform_initializer(minval=0, maxval=1).__call__((4,4))

In [36]:
my_ops = [const, fill_mat, myseros, ones, rand, rand_unif]

In [38]:
for op in my_ops:
    tf.print(op)
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


[[-1.08524477 -0.39079532 1.02901268 0.648397446]
 [-1.64218307 -0.278475225 0.61052686 -0.58121568]
 [0.464228898 0.168017596 1.47963393 1.48003519]
 [0.850544512 -1.38379741 0.678833246 0.135727733]]


[[0.269886136 0.045814395 0.00689518452 0.327914238]
 [0.523178697 0.773577571 0.217767358 0.163585663]
 [0.42932725 0.493098855 0.49363482 0.86211]
 [0.96742332 0.51721406 0.241227269 0.803702]]




In [56]:
a = tf.constant([ [1,2],
                  [3,4] ])
b = tf.constant([ [10], [100] ])

In [57]:
a.get_shape()

TensorShape([2, 2])

In [58]:
b.get_shape()

TensorShape([2, 1])

In [60]:
res = tf.matmul(a,b)

In [61]:
tf.print(res)

[[210]
 [430]]
